language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

branches:
  only:
    - master
    - stable
    - test

before_script:
  - psql -c 'create database crypton_test;' -U postgres

script: "cd server && make test"
