---

- name: create crypton database
  tags: createdb
  sudo: True
  sudo_user: postgres
  postgresql_db: >
    state=present
    name={{ crypton_db.name }}
    owner=postgres
    lc_collate=en_US.UTF-8
    encoding=UTF8
  register: create_crypton_database
  when: >
    development or create_crypton_db|default(False)

- name: create crypton central database users
  tags: pg_db_user
  postgresql_user: >
    state=present
    name={{crypton_db.username}}
    db={{crypton_db.name}}
    password={{crypton_db.password}}
  sudo: True
  sudo_user: postgres

- name: copy crypton database schema setup file
  tags: createdb
  sudo: True
  sudo_user: postgres
  copy: >
    src=setup.sql
    dest={{ role_org_dir }}/setup.sql
    backup=yes
    owner=postgres
    group=postgres
    mode=600
  when: >
    create_crypton_database is defined
    and create_crypton_database.changed

- name: install crypton database schema
  tags: createdb
  sudo: True
  sudo_user: postgres
  command: >
    /usr/bin/psql
    --echo-queries
    --file={{ role_org_dir }}/setup.sql
    --log-file={{ role_org_dir }}/setup.sql.log.{{ timestamp }}
    --dbname={{ crypton_db.name }}
  when: >
    create_crypton_database is defined
    and create_crypton_database.changed

- name: copy crypton database permissions template
  tags: createdb
  sudo: True
  sudo_user: postgres
  template: >
    src=permissions.sql.j2
    dest={{ role_org_dir }}/permissions.sql
    backup=yes
    owner=postgres
    group=postgres
    mode=600
  when: >
    create_crypton_database is defined
    and create_crypton_database.changed

- name: install crypton database permissions
  tags: createdb
  sudo: True
  sudo_user: postgres
  command: >
    /usr/bin/psql
    --echo-queries
    --file={{ role_org_dir }}/permissions.sql
    --log-file={{ role_org_dir }}/permissions.sql.log.{{ timestamp }}
    --dbname={{ crypton_db.name }}
  when: >
    create_crypton_database is defined
    and create_crypton_database.changed
