---

- name: install psycopg2
  apt: pkg=python-psycopg2 state=installed
  sudo: True

- name: make role organizational dir
  sudo: True
  file: >
    state=directory
    path={{ role_org_dir }}
    owner=postgres
    group=postgres
    mode=0700

- include: master.yml tags=role_crypton_db,crypton_db_master
  when: >
    inventory_hostname == database_master

- include: slaves.yml tags=role_crypton_db,crypton_db_slaves
  when: >
    inventory_hostname != database_master
