# production, not dev
development: False
production: True
deployment_environment: production

crypton_source_repository: https://github.com/SpiderOak/crypton.git
crypton_checkout: "/home/crypton_server/crypton"

crypton_server_domain: crypton.io
crypton_server_local_port: 40087

database_master: "{{ inventory_hostname }}"
# no db slaves present
database_slaves: []

# is it a dedicated db server machine that does nothing else?
pg_dedicated: True
