---

- hosts: all
  roles:
    - base

- hosts: database
  roles:
    - postgresql_server
    - postgresql_client
    - crypton_db

- hosts: web
  roles:
    - nginx

- hosts: redis
  roles:
    - redis

- hosts: crypton
  roles:
    - postgresql_client
    - nodejs
    - crypton_server

- hosts: dev_proxy
  roles:
   - dev_proxy
